# Generated by Django 2.2 on 2019-05-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_videos_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='file',
        ),
        migrations.AddField(
            model_name='videos',
            name='video_url',
            field=models.CharField(default='no-video', max_length=200),
        ),
    ]
